swagger: '2.0'
info:
  description: API Rest para cadastro de pessoas
  version: 1.0.0
  title: API Rest - PEOPLE
  contact:
    name: LivSun Devs
    url: 'https://github.com/DenilsonMarcio'
    email: denilson.santos7@fatec.sp.gov.br
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: api-rest-person.herokuapp.com
basePath: /
tags:
  - name: person-controller
    description: Person Controller
paths:
  /api/v1/people:
    get:
      tags:
        - person-controller
      summary: Retorna uma lista de pessoas
      operationId: listAllUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: Retorna a lista de pessoa
          schema:
            type: array
            items:
              $ref: '#/definitions/PersonDTO'
        '401':
          description: Unauthorized
        '403':
          description: Você não tem permissão para acessar este recurso
        '404':
          description: Not Found
        '500':
          description: Foi gerada uma exceção
    post:
      tags:
        - person-controller
      summary: Adiciona uma nova pessoa
      operationId: createPersonUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: personDTO
          description: personDTO
          required: true
          schema:
            $ref: '#/definitions/PersonDTO'
      responses:
        '201':
          description: Adicionado com sucesso
          schema:
            $ref: '#/definitions/MessageResponseDTO'
        '401':
          description: Unauthorized
        '403':
          description: Você não tem permissão para acessar este recurso
        '404':
          description: Not Found
        '500':
          description: Foi gerada uma exceção
  '/api/v1/people/{id}':
    get:
      tags:
        - person-controller
      summary: Retorna pessoa por ID
      operationId: findByIdUsingGET
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Retorna pessoa por ID
          schema:
            $ref: '#/definitions/PersonDTO'
        '401':
          description: Unauthorized
        '403':
          description: Você não tem permissão para acessar este recurso
        '404':
          description: Not Found
        '500':
          description: Foi gerada uma exceção
    put:
      tags:
        - person-controller
      summary: Atualiza pessoa por ID
      operationId: updateByIdUsingPUT
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int64
        - in: body
          name: personDTO
          description: personDTO
          required: true
          schema:
            $ref: '#/definitions/PersonDTO'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/MessageResponseDTO'
        '201':
          description: Created
        '204':
          description: Atualizado com sucesso
        '401':
          description: Unauthorized
        '403':
          description: Você não tem permissão para acessar este recurso
        '404':
          description: Not Found
        '500':
          description: Foi gerada uma exceção
    delete:
      tags:
        - person-controller
      summary: Deleta pessoa por ID
      operationId: deleteByIdUsingDELETE
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int64
      responses:
        '204':
          description: Deletado com sucesso
        '401':
          description: Unauthorized
        '403':
          description: Você não tem permissão para acessar este recurso
        '500':
          description: Foi gerada uma exceção
definitions:
  MessageResponseDTO:
    type: object
    properties:
      message:
        type: string
    title: MessageResponseDTO
  PersonDTO:
    type: object
    properties:
      birthDate:
        type: string
        example: "06-04-1982"
      cpf:
        type: string
        example: "679.537.790-30"
      firstName:
        type: string
        example: "Cleyton"
      id:
        type: integer
        format: int64
      lastName:
        type: string
        example: "Alves"
      phones:
        type: array
        items:
          $ref: '#/definitions/PhoneDTO'
    title: PersonDTO
  PhoneDTO:
    type: object
    properties:
      id:
        type: integer
        format: int64
      number:
        type: string
        example: "(11)98888-8888"
      type:
        type: string
        enum:
          - COMMERCIAL
          - HOME
          - MOBILE
    title: PhoneDTO
